### ISSUE TITLE
How to remove the specification group name from the tabs

### ISSUE THREAD

**Issue by prithi** [dornaweb/product-specifications#1]
How can I remove the group name from the product specification tabs?

![screenshot-2018-1-4 anker powerline lightning cable 1 8m 6ft penguin com bd](https://user-images.githubusercontent.com/2114722/34543132-927bd754-f109-11e7-876e-50f422c3f4c8.png)

![screenshot-2018-1-4 attribute groups penguin com bd wordpress](https://user-images.githubusercontent.com/2114722/34543138-9ba4004a-f109-11e7-895e-e7dcdd98fb55.png)

**Comment by amiut** [comment]
As for now you can hide it with CSS : 
``
.dwspecs-product-table-group .group-title{
  display: none;
}
``

To make sure that you don't hide group names that are needed i suggest to remove only the first group name, because as i can guess you wan't a single group table:
``
.dwspecs-product-table-group:first-child .group-title{
  display: none;
}
``

**Comment by prithi** [comment]
Thank you so much.
